### ISSUE TITLE
New dependency issue

### ISSUE THREAD

**Issue by tmcclintock** [Samreay/SurveyVisualiser#3]
In a recent commit you added sncosmo as a dependence on line 2 of surveyvis/survey.py. This module is only used for the SupernovaSurvey class and broke my fork (in which I'm not working on SNIa :)).

This dependency should be moved inside the class that uses it to cut down on dependencies for general use.

**Comment by Samreay** [comment]
My bad on this one. Have a summer student that is working on the project and pulled in their pull request. Theres a few more issues here than just the new dependency too. I went ahead and made a refactor branch to fix the issues and show them a slightly refactored OO approach to the solution, which has everything fixed (and sncosmo imported only inside the supernova class). I had this on the refactor branch, but have turned master into the hugh branch and refactor into the master branch so that if you update your fork all issues should be solved.

Let me know if there is anything outstanding after you pull in. Sorry for the hassle!
